### ISSUE TITLE
Main interface's does not deal with accepting follow request

### ISSUE THREAD

**Issue by aholgate** [CMPUT301F17T07/inGroove#2]
@AustinGrey 

Has to do with the following use case: 
CW - Use Case 11: Approve Follow requests
User Stories - US 05.02.01
Goal: User Approves a follow request
Trigger: a follow request is made by another User
Precondition: another User has requested to follow you
Postcondition: The User is being followed by the other User
Basic Flow:
    1. The app notifies the User that they have a follow request
    2. The User opens the app
    3. The User selects the follow request
    4. The app prompts the User to approve or reject the follow request
    5. The User approves the follow request
    6. The app adds the other User to the Users Followers

Add something like this to the main interface file please and thank you!
![follow_request](https://user-images.githubusercontent.com/31749025/31521647-8edeff38-af67-11e7-89f1-0def53150ba4.png)

**Comment by AustinGrey** [comment]
The interface has been redone with the requested content. I also added a delete button to delete requests because it was simple and seemed important.
