### ISSUE TITLE
Look into what will fit better for the project, using a Calendar or using Date

### ISSUE THREAD

**Issue by AustinGrey** [CMPUT301F17T07/inGroove#22]
Calendars can help us with relative dates better than Date can it seems. So we can get the date 1 week earlier for example, or a month from now without worrying about the dreaded February 30th

**Comment by aholgate** [comment]
Thing to note, looking through the different elements that you can place in a view, there is a "CalendarView" option. Should look into this more and see if it's something we want to use ?
