### ISSUE TITLE
UML Diagram needs Boundary, Control, Entity structure

### ISSUE THREAD

**Issue by AustinGrey** [CMPUT301F17T07/inGroove#6]
Prof. said that the UML diagram needs boundary control entity classes. Each should be labelled as such, eg << Entity >>. However the tests are only for the entity model classes. We need to update the UML since it only has entity classes, and they aren't labeled.

**Comment by fbulbuc** [comment]
Let's discuss this issue further in our Friday meeting?

**Comment by fbulbuc** [comment]
issued was resolved during our meeting.
